name: automerge
on:
  pull_request:
    types:
      - edited
      - labeled
      - opened
      - ready_for_review
      - reopened
      - synchronize
      - unlabeled
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.7.5"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_DELETE_BRANCH: "true"
          MERGE_LABELS: "automerge,¡trabajo en proceso!"
          MERGE_METHOD: "rebase"
          # Deshabilité los PR de base automática porque no pueden volver a activar las comprobaciones
          UPDATE_LABELS: ""
          UPDATE_METHOD: "rebase"
          # Nuestro CI tarda unos 15 m en completarse; sigue intentando por 30m
          MERGE_RETRIES: 30
          MERGE_RETRY_SLEEP: 60000
